NETCKTEAM30/NETCKTEAM30/Models/NguoiDung.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NETCKTEAM30.Models
{
    public class NguoiDung
    {
        public int NguoiDungID { get; set; }
        public string HoTen { get; set; }
        public int GioiTinhID { get; set; }
        [ForeignKey("GioiTinhID")]
        public GioiTinh GioiTinh { get; set; }
        public DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string Hinh { get; set; }
        public int LoaiNgDungID { get; set; }
        [ForeignKey("LoaiNgDungID")]
        public LoaiNgDung LoaiNgDung { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    }
}

NETCKTEAM30/NETCKTEAM30/Controllers/NguoiDungsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NETCKTEAM30.Models;

namespace NETCKTEAM30.Controllers
{
    public class NguoiDungsController : Controller
    {
        private readonly MyDbContext _context;

        public NguoiDungsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: NguoiDungs
        public async Task<IActionResult> Index()
        {
            var myDbContext = _context.NguoiDungs.Include(n => n.GioiTinh).Include(n => n.LoaiNgDung);
            return View(await myDbContext.ToListAsync());
        }

        // GET: NguoiDungs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nguoiDung = await _context.NguoiDungs
                .Include(n => n.GioiTinh)
                .Include(n => n.LoaiNgDung)
                .FirstOrDefaultAsync(m => m.NguoiDungID == id);
            if (nguoiDung == null)
            {
                return NotFound();
            }
            string[] arrListStr = nguoiDung.Hinh.Split(';');
            ViewBag.arr = arrListStr;
            return View(nguoiDung);
        }

        // GET: NguoiDungs/Create
        public IActionResult Create()
        {
            ViewData["GioiTinhID"] = new SelectList(_context.GioiTinhs, "GioiTinhID", "TenGT");
            ViewData["LoaiNgDungID"] = new SelectList(_context.LoaiNgDungs, "LoaiNgDungID", "TenLoai");
            return View();
        }

        // POST: NguoiDungs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NguoiDungID,HoTen,GioiTinhID,NgaySinh,DiaChi,SDT,Email,Hinh,LoaiNgDungID,TenDangNhap,MatKhau")] NguoiDung nguoiDung, IFormFile[] myfile)
        {
            if (ModelState.IsValid)
            {
                string arr = "";

                if (myfile != null)
                {
                    foreach (var item in myfile)
                    {
                        string url = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", item.FileName);
                        using (var f = new FileStream(url, FileMode.Create))
                        {
                            item.CopyTo(f);
                        }
                        arr += item.FileName;
                    }
                    nguoiDung.Hinh = arr;
                }
                _context.Add(nguoiDung);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GioiTinhID"] = new SelectList(_context.GioiTinhs, "GioiTinhID", "GioiTinhID", nguoiDung.GioiTinhID);
            ViewData["LoaiNgDungID"] = new SelectList(_context.LoaiNgDungs, "LoaiNgDungID", "LoaiNgDungID", nguoiDung.LoaiNgDungID);
            return View(nguoiDung);
        }

        // GET: NguoiDungs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nguoiDung = await _context.NguoiDungs.FindAsync(id);
            if (nguoiDung == null)
            {
                return NotFound();
            }
            ViewData["GioiTinhID"] = new SelectList(_context.GioiTinhs, "GioiTinhID", "TenGT", nguoiDung.GioiTinhID);
            ViewData["LoaiNgDungID"] = new SelectList(_context.LoaiNgDungs, "LoaiNgDungID", "TenLoai", nguoiDung.LoaiNgDungID);
            string[] arrListStr = nguoiDung.Hinh.Split(';');
            ViewBag.arr = arrListStr;
            return View(nguoiDung);
        }

        // POST: NguoiDungs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NguoiDungID,HoTen,GioiTinhID,NgaySinh,DiaChi,SDT,Email,Hinh,LoaiNgDungID,TenDangNhap,MatKhau")] NguoiDung nguoiDung, IFormFile[] myfile)
        {
            if (id != nguoiDung.NguoiDungID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string arr = "";

                    if (myfile != null)
                    {
                        foreach (var item in myfile)
                        {
                            string url = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", item.FileName);
                            using (var f = new FileStream(url, FileMode.Create))
                            {
                                item.CopyTo(f);
                            }
                            arr += item.FileName;
                        }
                        nguoiDung.Hinh = arr;
                    }
                    _context.Update(nguoiDung);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NguoiDungExists(nguoiDung.NguoiDungID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GioiTinhID"] = new SelectList(_context.GioiTinhs, "GioiTinhID", "GioiTinhID", nguoiDung.GioiTinhID);
            ViewData["LoaiNgDungID"] = new SelectList(_context.LoaiNgDungs, "LoaiNgDungID", "LoaiNgDungID", nguoiDung.LoaiNgDungID);
            return View(nguoiDung);
        }

        // GET: NguoiDungs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nguoiDung = await _context.NguoiDungs
                .Include(n => n.GioiTinh)
                .Include(n => n.LoaiNgDung)
                .FirstOrDefaultAsync(m => m.NguoiDungID == id);
            if (nguoiDung == null)
            {
                return NotFound();
            }

            return View(nguoiDung);
        }

        // POST: NguoiDungs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nguoiDung = await _context.NguoiDungs.FindAsync(id);
            _context.NguoiDungs.Remove(nguoiDung);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NguoiDungExists(int id)
        {
            return _context.NguoiDungs.Any(e => e.NguoiDungID == id);
        }
        public IActionResult dangnhap()
        {
            return View();
        }
        [HttpPost]
        public IActionResult dangnhap(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                NguoiDung kh = _context.NguoiDungs.SingleOrDefault(p => p.TenDangNhap == model.MaKH && p.MatKhau == model.MatKhau);
                if (kh == null)
                {
                    ModelState.AddModelError("Loi", "Không có khách hàng này.");
                    return View();
                }

                HttpContext.Session.Set("MaKH", kh);
                HttpContext.Session.Set<int>("a", 1);
                return RedirectToAction("index", "Home");
            }
            else
            {
                return RedirectToAction("index", "Home");
            }

        }
        public IActionResult dangky()
        {
            ViewData["GioiTinhID"] = new SelectList(_context.GioiTinhs, "GioiTinhID", "TenGT");
            ViewData["LoaiNgDungID"] = new SelectList(_context.LoaiNgDungs, "LoaiNgDungID", "TenLoai");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> dangky([Bind("NguoiDungID,HoTen,GioiTinhID,NgaySinh,DiaChi,SDT,Email,Hinh,TenDangNhap,MatKhau")] NguoiDung nguoiDung, IFormFile[] myfile)
        {
            if (ModelState.IsValid)
            {
                string arr = "";

                if (myfile != null)
                {
                    foreach (var item in myfile)
                    {
                        string url = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", item.FileName);
                        using (var f = new FileStream(url, FileMode.Create))
                        {
                            item.CopyTo(f);
                        }
                        arr += item.FileName;
                    }
                    nguoiDung.Hinh = arr;
                    nguoiDung.LoaiNgDungID = 3;
                }
                _context.Add(nguoiDung);
                HttpContext.Session.Set<int>("a", 2);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), "Home");
            }
            ViewData["GioiTinhID"] = new SelectList(_context.GioiTinhs, "GioiTinhID", "GioiTinhID", nguoiDung.GioiTinhID);
            ViewData["LoaiNgDungID"] = new SelectList(_context.LoaiNgDungs, "LoaiNgDungID", "LoaiNgDungID", nguoiDung.LoaiNgDungID);
            return View(nguoiDung);
        }
        [HttpGet]
        public IActionResult suathongtinkh(int id)
        {

NETCKTEAM30/NETCKTEAM30/Views/NguoiDungs/Create.cshtml
@model NETCKTEAM30.Models.NguoiDung

@{
    ViewData["Title"] = "Create";
}


@{
    Layout = "_Admin";
}
<head>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        .mainmenu{
            margin-left: 24%;
        }
    </style>
</head>
<body>
    <h3 class="w3-bar-item w3-padding w3-white" style="width:100%; text-align: center">ACCOUNTS</h3>
    <hr />
    <div class="row mainmenu">
        <div class="col-md-8">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    Họ Tên
                    <input asp-for="HoTen" class="form-control" />
                    <span asp-validation-for="HoTen" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Giới Tính
                    <select asp-for="GioiTinhID" class="form-control" asp-items="ViewBag.GioiTinhID"></select>
                </div>
                <div class="form-group">
                    Ngày Sinh
                    <input asp-for="NgaySinh" class="form-control" />
                    <span asp-validation-for="NgaySinh" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Địa chỉ
                    <input asp-for="DiaChi" class="form-control" />
                    <span asp-validation-for="DiaChi" class="text-danger"></span>
                </div>
                <div class="form-group">
                    SĐT
                    <input asp-for="SDT" class="form-control" />
                    <span asp-validation-for="SDT" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Email
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Hình

                    <input type="file" name="myfile" multiple />
                    <span asp-validation-for="Hinh" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Loại Người Dùng
                    <select asp-for="LoaiNgDungID" class="form-control" asp-items="ViewBag.LoaiNgDungID"></select>
                </div>
                <div class="form-group">
                    Tên Đăng Nhập
                    <input asp-for="TenDangNhap" class="form-control" />
                    <span asp-validation-for="TenDangNhap" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Mật Khẩu
                    <input asp-for="MatKhau" type="password" class="form-control" />
                    <span asp-validation-for="MatKhau" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Thêm" class="w3-bar-item w3-padding w3-pale-red" />
                    <a asp-action="Index" class="w3-bar-item w3-padding w3-pale-blue w3-button">Trở Về</a>
                </div>
            </form>
        </div>
    </div>
</body>

NETCKTEAM30/NETCKTEAM30/Views/NguoiDungs/Delete.cshtml
@model NETCKTEAM30.Models.NguoiDung

@{
    ViewData["Title"] = "Delete";
}
@{
    Layout = "_Admin";
}
<head>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        .mainmenu {
            margin-left: 30%;
        }

        table, tr, td {
            border: 1px solid black;
            border-collapse: collapse;
            background-color: white;
        }

        tr, td {
            padding: 10px;
        }
    </style>
</head>
<body>
    <h3 class="w3-bar-item w3-padding w3-white" style="width:100%; text-align: center">ACCOUNTS</h3>
    <br />
    <br />
    <div class="mainmenu">
        <h4>Bán Muốn Xóa Người Dùng Này ?</h4>
        <hr />
        <table>
            <tr>
                <td>Họ Tên: </td>
                <td> @Html.DisplayFor(model => model.HoTen)</td>
            </tr>
            <tr>
                <td>Giới tính: </td>
                <td> @Html.DisplayFor(model => model.GioiTinh.TenGT)</td>
            </tr>
            <tr>
                <td>Ngày Sinh: </td>
                <td> @Html.DisplayFor(model => model.NgaySinh)</td>
            </tr>
            <tr>
                <td>Địa Chỉ: </td>
                <td> @Html.DisplayFor(model => model.DiaChi)</td>
            </tr>
            <tr>
                <td>SĐT: </td>
                <td> @Html.DisplayFor(model => model.SDT)</td>
            </tr>
            <tr>
                <td>Email: </td>
                <td> @Html.DisplayFor(model => model.Email)</td>
            </tr>
            <tr>
                <td>Ảnh đại diện: </td>
                <td><img style="width:170px;height:150px;float:left; padding:5px;" src="~/images/@Html.DisplayFor(model => model.Hinh)" class="img-thumbnail" alt="Cinque Terre" /></td>
            </tr>
            <tr>
                <td>Loại Người Dùng: </td>
                <td> @Html.DisplayFor(model => model.LoaiNgDung.TenLoai)</td>
            </tr>
            <tr>
                <td>Tên Đăng Nhập: </td>
                <td> @Html.DisplayFor(model => model.TenDangNhap)</td>
            </tr>
        </table>
        <br />
        <br />
        <form asp-action="Delete">
            <input type="hidden" asp-for="NguoiDungID" />
            <input type="submit" value="Xóa" class="w3-bar-item w3-padding w3-pale-red w3-button" />
            <a asp-action="Index" class="w3-bar-item w3-padding w3-pale-blue w3-button">Trở Về</a>
        </form>
    </div>
</body>

NETCKTEAM30/NETCKTEAM30/Views/NguoiDungs/Details.cshtml
@model NETCKTEAM30.Models.NguoiDung

@{
    ViewData["Title"] = "Details";
}

@{
    Layout = "_Admin";
}
<head>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        .mainmenu {
            margin-left:30%;
        }
        table, tr,td{
            border: 1px solid black;
            border-collapse: collapse;
            background-color: white;
        }
        tr,td{
            padding: 10px;
        }
    </style>
</head>
<body>
    <h3 class="w3-bar-item w3-padding w3-white" style="width:100%; text-align: center">PRODUCTS</h3>
    <br />
    <br />
    <table class="mainmenu">
        <tr>
            <td>Họ Tên: </td>
            <td> @Html.DisplayFor(model => model.HoTen)</td>
        </tr>
        <tr>
            <td>Giới tính: </td>
            <td> @Html.DisplayFor(model => model.GioiTinh.TenGT)</td>
        </tr>
        <tr>
            <td>Ngày Sinh: </td>
            <td> @Html.DisplayFor(model => model.NgaySinh)</td>
        </tr>
        <tr>
            <td>Địa Chỉ: </td>
            <td> @Html.DisplayFor(model => model.DiaChi)</td>
        </tr>
        <tr>
            <td>SĐT: </td>
            <td> @Html.DisplayFor(model => model.SDT)</td>
        </tr>
        <tr>
            <td>Email: </td>
            <td> @Html.DisplayFor(model => model.Email)</td>
        </tr>
        <tr>
            <td>Ảnh đại diện: </td>
            <td> 
                <div style="width:auto;height:200px; ">
                  @foreach (var item in ViewBag.arr)
                    {
                        if (item != "")
                        {
                        <img style="width:220px;height:200px;float:left; padding:5px;" src="~/images/@item" class="img-thumbnail" alt="Cinque Terre" />

                    }
                }
                </div>
            </td>
        </tr>
        <tr>
            <td>Loại Người Dùng: </td>
            <td> @Html.DisplayFor(model => model.LoaiNgDung.TenLoai)</td>
        </tr>
        <tr>
            <td>Tên Đăng Nhập: </td>
            <td> @Html.DisplayFor(model => model.TenDangNhap)</td>
        </tr>
    </table>
    <br />
    <br />
    <div class="mainmenu">
        <a asp-action="Edit" asp-route-id="@Model.NguoiDungID" class="w3-bar-item w3-padding w3-pale-yellow w3-button">Sửa</a>
        <a asp-action="Delete" asp-route-id="@Model.NguoiDungID" class="w3-bar-item w3-padding w3-pale-red w3-button">Xóa</a>
        <a asp-action="Index" class="w3-bar-item w3-padding w3-pale-blue w3-button">Trở Về</a>
    </div>
</body>

NETCKTEAM30/NETCKTEAM30/Views/NguoiDungs/dangky.cshtml
@model NETCKTEAM30.Models.NguoiDung

@{
    ViewData["Title"] = "Create";
}


<meta name="viewport" content="width=device-width" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/css/mycss.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


<body>



    <hr />
    <div id="id01" class="modal" style="display:block;">

        <form class="modal-content animate" asp-action="dangky" asp-controller="NguoiDungs" style="width:30%;"enctype="multipart/form-data">
            <div class="imgcontainer">
                <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
                <img src="~/images/img_avatar2.png" alt="Avatar" class="avatar">
            </div>

            <div class="container">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    Họ Tên
                    <br />
                    <input asp-for="HoTen" class="form-control inputdangky" />
                    <span asp-validation-for="HoTen" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Giới Tính
                    <select asp-for="GioiTinhID" class="form-control inputdangky" asp-items="ViewBag.GioiTinhID"></select>
                    <br />
                </div>
                <div class="form-group">
                    Ngày Sinh
                    <input asp-for="NgaySinh" class="form-control inputdangky" />
                    <span asp-validation-for="NgaySinh" class="text-danger"></span>
                    <br />
                </div>
                <div class="form-group">
                    Địa Chỉ
                    <br />
                    <input asp-for="DiaChi" class="form-control inputdangky" />
                    <span asp-validation-for="DiaChi" class="text-danger"></span>
                </div>
                <div class="form-group">
                    SĐT
                    <br />
                    <input asp-for="SDT" class="form-control inputdangky" />
                    <span asp-validation-for="SDT" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Email
                    <br />
                    <input asp-for="Email" class="form-control inputdangky" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Hình

                    <input type="file" name="myfile" multiple />
                    <span asp-validation-for="Hinh" class="text-danger"></span>
                </div>

                <div class="form-group">
                    Tên Đăng Nhập
                    <input asp-for="TenDangNhap" class="form-control inputdangky" />
                    <span asp-validation-for="TenDangNhap" class="text-danger"></span>
                </div>
                <div class="form-group">
                    Mật Khẩu
                    <br />
                    <input asp-for="MatKhau" class="form-control inputdangky" />
                    <span asp-validation-for="MatKhau" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Đăng Ký" class="btn btn-default btn btn-info buttomlogin" />
                </div>
                <br />
                <label>
                    <input type="checkbox" checked="checked" name="remember"> Remember me
                </label>
            </div>

            <div class="container " style="background-color:#f1f1f1;width:100%;">
                <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>

                <span class="psw">Forgot <a href="#">password?</a></span>
            </div>
        </form>
    </div>
   
</body>

NETCKTEAM30/NETCKTEAM30/Views/NguoiDungs/dangnhap.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "dangnhap";
}
<meta name="viewport" content="width=device-width" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/css/mycss.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<body>



    <div id="id01" class="modal" style="display:block;">

        <form class="modal-content animate" asp-action="dangnhap" asp-controller="NguoiDungs" style="width:30%;" >
            <div class="imgcontainer">
                <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
                <img src="~/images/img_avatar2.png" alt="Avatar" class="avatar">
            </div>

            <div class="container">
                <div class="form-group">
                    <label asp-for="MaKH" class="control-label"></label>
                    <input asp-for="MaKH" class="form-control" name="MaKH" style="width:29%;" />
                    <span asp-validation-for="MaKH" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MatKhau" class="control-label"></label>
                    <input asp-for="MatKhau" class="form-control" name="MatKhau" style="width:29%;"/>
                    <span asp-validation-for="MatKhau" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <button class="buttomlogin" type="submit">Login</button>
                </div>

                <a asp-action="dangky" asp-controller="NguoiDungs" class="btn btn-info buttomlogin" >Đăng Ký</a>
                <br />
                <label>
                    <input type="checkbox" checked="checked" name="remember"> Remember me
                </label>
            </div>

            <div class="container" style="background-color:#f1f1f1; width:100%;">
                <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>

                <span class="psw">Forgot <a href="#">password?</a></span>
            </div>
        </form>
    </div>

    <script>
        // Get the modal
        var modal = document.getElementById('id01');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>

</body>

NETCKTEAM30/NETCKTEAM30/Views/NguoiDungs/suathongtinkh.cshtml
@model NETCKTEAM30.Models.NguoiDung

@{
    ViewData["Title"] = "suathongtinkh";
}

<meta name="viewport" content="width=device-width" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/css/mycss.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


<h2>Sửa Thông Tin cá Nhân</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="suathongtinkh" asp-controller="NguoiDungs" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NguoiDungID" />
            <div class="form-group">
                Họ Tên
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                Giới Tính
                <select asp-for="GioiTinhID" class="form-control" asp-items="ViewBag.GioiTinhID"></select>
                <span asp-validation-for="GioiTinhID" class="text-danger"></span>
            </div>
            <div class="form-group">
                Ngày Sinh
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                Địa Chỉ
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                SĐT
                <input asp-for="SDT" class="form-control" />
                <span asp-validation-for="SDT" class="text-danger"></span>
            </div>
            <div class="form-group">
                Email
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                Hình
                <dd>
                    <div style="width:auto;height:210px; ">

                        <img style="width:220px;height:200px;float:left; padding:5px;" src="~/images/@Model.Hinh" class="img-thumbnail" alt="Cinque Terre" />


                    </div>
                </dd>
                Khác
                <input type="file" name="myfile" multiple />
                <span asp-validation-for="Hinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" value="@Model.LoaiNgDungID" name="lngd" />

            </div>
            <div class="form-group">
                Tên Đăng nhập
                <input asp-for="TenDangNhap" class="form-control" />
                <span asp-validation-for="TenDangNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                Mật Khẩu
                <input asp-for="MatKhau" type="password" class="form-control" />

            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-default btn btn-info" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home" class="btn btn-info">Trở Về</a>
</div>