NETCKTEAM30/NETCKTEAM30/Models/HangHoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NETCKTEAM30.Models
{
    public class HangHoa
    {
        public int HanghoaID { get; set; }
        public string TenHh { get; set; }
        public int MaLoaiID { get; set; }
        [ForeignKey("MaLoaiID")]
        public Loai Loai { get; set; }
        public double DonGia { get; set;}
        public string Hinh { get; set; }
        public int NhaCungCapID { get; set; }
        [ForeignKey("NhaCungCapID")]
        public NhaCungCap NhaCungCap { get; set; }
        public DateTime NgayNhap { get; set; }
        public string MoTa { get; set; }
        public double GiamGia { get; set; }
        public int LuotMua { get; set; }
    }
}

NETCKTEAM30/NETCKTEAM30/Models/HangHoaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETCKTEAM30.Models
{
    public class HangHoaViewModel
    {
        public int MaHH { get; set; }
        public string TenHH { get; set; }
        public string Hinh { get; set; }
        public double DonGia { get; set; }
        public double GiamGia { get; set; }
        public double GiaBan => DonGia * (1 - GiamGia);
        public bool DangKhuyenMai => GiamGia > 0;
    }
}

NETCKTEAM30/NETCKTEAM30/Models/chitietViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETCKTEAM30.Models
{
    public class chitietViewModel
    {
        public HangHoa don { get; set; }
        public List<HangHoa> dhhhcungloai { get; set; }
        public List<HangHoa> dhhhcungncc { get; set; }
        public List<BinhLuan> bluans { get; set; }
    }
}

NETCKTEAM30/NETCKTEAM30/Controllers/HangHoasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NETCKTEAM30.Models;

namespace NETCKTEAM30.Controllers
{
    public class HangHoasController : Controller
    {
        private readonly MyDbContext _context;

        public HangHoasController(MyDbContext context)
        {
            _context = context;
        }

        // GET: HangHoas
        public async Task<IActionResult> Index()
        {
            var myDbContext = _context.HangHoas.Include(h => h.Loai).Include(h => h.NhaCungCap);

            return View(await myDbContext.ToListAsync());
        }

        // GET: HangHoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.Loai)
                .Include(h => h.NhaCungCap)
                .FirstOrDefaultAsync(m => m.HanghoaID == id);
            if (hangHoa == null)
            {
                return NotFound();
            }
            string[] arrListStr = hangHoa.Hinh.Split(';');
            ViewBag.arr = arrListStr;
            return View(hangHoa);
        }

        // GET: HangHoas/Create
        public IActionResult Create()
        {
            ViewData["MaLoaiID"] = new SelectList(_context.Loais, "LoaiID", "TenLoai");
            ViewData["NhaCungCapID"] = new SelectList(_context.NhaCungCaps, "NhaCungCapID", "TenNhaCc");
            return View();
        }

        // POST: HangHoas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HanghoaID,TenHh,MaLoaiID,DonGia,Hinh,NhaCungCapID,NgayNhap,MoTa,GiamGia,LuotMua")] HangHoa hangHoa, IFormFile[] myfile)
        {

            if (ModelState.IsValid)
            {
                string arr = "";

                if (myfile != null)
                {
                    foreach (var item in myfile)
                    {
                        string url = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", item.FileName);
                        using (var f = new FileStream(url, FileMode.Create))
                        {
                            item.CopyTo(f);
                        }
                        arr += item.FileName;
                    }
                    hangHoa.Hinh = arr;
                }
                _context.Add(hangHoa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoaiID"] = new SelectList(_context.Loais, "LoaiID", "LoaiID", hangHoa.MaLoaiID);
            ViewData["NhaCungCapID"] = new SelectList(_context.NhaCungCaps, "NhaCungCapID", "NhaCungCapID", hangHoa.NhaCungCapID);
            return View(hangHoa);
        }

        // GET: HangHoas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas.FindAsync(id);
            if (hangHoa == null)
            {
                return NotFound();
            }
            ViewData["MaLoaiID"] = new SelectList(_context.Loais, "LoaiID", "TenLoai", hangHoa.MaLoaiID);
            ViewData["NhaCungCapID"] = new SelectList(_context.NhaCungCaps, "NhaCungCapID", "TenNhaCc", hangHoa.NhaCungCapID);
            string[] arrListStr = hangHoa.Hinh.Split(';');
            ViewBag.arr = arrListStr;
            return View(hangHoa);
        }

        // POST: HangHoas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("HanghoaID,TenHh,MaLoaiID,DonGia,Hinh,NhaCungCapID,NgayNhap,MoTa,GiamGia,LuotMua")] HangHoa hangHoa, IFormFile[] myfile)
        {
            if (id != hangHoa.HanghoaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string arr = "";

                    if (myfile != null)
                    {
                        foreach (var item in myfile)
                        {
                            string url = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", item.FileName);
                            using (var f = new FileStream(url, FileMode.Create))
                            {
                                item.CopyTo(f);
                            }
                            arr += item.FileName;
                        }
                        hangHoa.Hinh = arr;
                    }
                    _context.Update(hangHoa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HangHoaExists(hangHoa.HanghoaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoaiID"] = new SelectList(_context.Loais, "LoaiID", "LoaiID", hangHoa.MaLoaiID);
            ViewData["NhaCungCapID"] = new SelectList(_context.NhaCungCaps, "NhaCungCapID", "NhaCungCapID", hangHoa.NhaCungCapID);
            return View(hangHoa);
        }

        // GET: HangHoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hangHoa = await _context.HangHoas
                .Include(h => h.Loai)
                .Include(h => h.NhaCungCap)
                .FirstOrDefaultAsync(m => m.HanghoaID == id);
            if (hangHoa == null)
            {
                return NotFound();
            }

            return View(hangHoa);
        }

        // POST: HangHoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hangHoa = await _context.HangHoas.FindAsync(id);
            _context.HangHoas.Remove(hangHoa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HangHoaExists(int id)
        {
            return _context.HangHoas.Any(e => e.HanghoaID == id);
        }
        public IActionResult HangHoaTheoLoai(int? LoaiID, int? NhaCungCapID)
        {

            List<HangHoa> DsHh = new List<HangHoa>();
            if (LoaiID.HasValue)
            {
                DsHh = _context.HangHoas.Where(h => h.HanghoaID == LoaiID).ToList();
            }
            if (NhaCungCapID.HasValue)
            {
                DsHh = _context.HangHoas.Where(h => h.NhaCungCapID == NhaCungCapID).ToList();
            }
            return View(DsHh.Select(h => new HangHoaViewModel
            {
                MaHH = h.HanghoaID,
                TenHH = h.TenHh,
                Hinh = h.Hinh,
                DonGia = h.DonGia,
                GiamGia = h.GiamGia
            }));

        }
        public IActionResult selectAo()
        {
            List<HangHoa> DsHh = new List<HangHoa>();
            DsHh = _context.HangHoas.Where(h => h.MaLoaiID == 1).ToList();
            return View(DsHh.Select(h => new HangHoaViewModel
            {
                MaHH = h.HanghoaID,
                TenHH = h.TenHh,
                Hinh = h.Hinh,
                DonGia = h.DonGia,
                GiamGia = h.GiamGia
            }));
        }
        public IActionResult selectQuan()
        {
            List<HangHoa> DsHh = new List<HangHoa>();
            DsHh = _context.HangHoas.Where(h => h.MaLoaiID == 2).ToList();
            return View(DsHh.Select(h => new HangHoaViewModel
            {
                MaHH = h.HanghoaID,
                TenHH = h.TenHh,
                Hinh = h.Hinh,
                DonGia = h.DonGia,
                GiamGia = h.GiamGia
            }));
        }
        public IActionResult selectGiay()
        {
            List<HangHoa> DsHh = new List<HangHoa>();
            DsHh = _context.HangHoas.Where(h => h.MaLoaiID == 4).ToList();
            return View(DsHh.Select(h => new HangHoaViewModel
            {
                MaHH = h.HanghoaID,
                TenHH = h.TenHh,
                Hinh = h.Hinh,
                DonGia = h.DonGia,
                GiamGia = h.GiamGia
            }));
        }
        public IActionResult Search(string keyword = "")
        {
            if (keyword != null)
            {
                keyword = keyword.ToLower();
                var data = _context.HangHoas.Where(p => p.TenHh.ToLower().Contains(keyword))
                    .Select(p => new HangHoaViewModel
                    {
                        MaHH = p.HanghoaID,
                        TenHH = p.TenHh,
                        Hinh = p.Hinh,
                        DonGia = p.DonGia,
                        GiamGia = p.GiamGia
                    }).ToList();

                return PartialView(data);
            }
            else
            {
                return PartialView();
            }
        }

NETCKTEAM30/NETCKTEAM30/Views/HangHoas/Search.cshtml
@model IEnumerable<NETCKTEAM30.Models.HangHoaViewModel>
@{
    ViewData["Title"] = "Search";
}
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />

@foreach (var hh in Model)
{
   
    if (hh.GiamGia == 0)
    {
        <div class="col-sm-3">
            <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
               asp-route-id="@hh.MaHH">
                <img src="~/images/@hh.Hinh" style="height:310px;width:200px" />
                <span class="thongtinsanpham">
                    <h4 class="tensanpham">@hh.TenHH</h4>
                    <div class="danhmucsanpham">@hh.GiaBan $</div>
                </span>
            </a>
        </div>
    }
    else
    {
        double a = (double)hh.GiamGia * 100;
        hh.GiamGia = a;
        <div class="col-sm-3">
            <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
               asp-route-id="@hh.MaHH">

                <img src="~/images/@hh.Hinh" style="height:310px;width:200px" />
                <span class="thongtinsanpham">
                    <h4 class="tensanpham">@hh.TenHH</h4>
                    <span style="color:red;font-weight:700;font-size:20px;">GIẢM @hh.GiamGia %</span>
                    <div class="danhmucsanpham" style="text-decoration: line-through; float:left; margin-top:20px;">@hh.DonGia .000 đ</div>
                    @{
                        double b = (double)(hh.DonGia - ((double)((hh.DonGia * hh.GiamGia) / 100)));
                        hh.DonGia = b;
                    }
                    <div style="float:left;">
                        <span style="color: #0c0c0c;font-size: 10px;margin-left:10px;"> Chỉ còn:</span><span style="color:red;font-size:20px;font-weight:900;">@hh.DonGia .000 đ</span>
                    </div>

                </span>
            </a>
        </div>
    }


}

NETCKTEAM30/NETCKTEAM30/Views/HangHoas/chitiet.cshtml
@model NETCKTEAM30.Models.chitietViewModel
@{
    ViewData["Title"] = "chitiet";
}
<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<link href="~/css/mycss.css" rel="stylesheet" />

<div class="row">
    <div class="col-sm-4" style="height:500px;">
        <img src="~/images/@Model.don.Hinh" style="height:450px;" />
        <hr />
    </div>
    <div class="col-sm-4" style="height:500px;">
        <h1 style="color:black;font-weight:700">@Model.don.TenHh</h1>
        <hr />
        <h4>Mô Tả:</h4>
        <p>@Model.don.MoTa</p>
        <br />
        <h4>Giá bán:<span style="color:coral;font-size:30px;"> @Model.don.DonGia .000 đ</span></h4>
        <br />
        <form asp-action="mua" asp-controller="HangHoas" method="post">
            <input type="hidden" value="@Model.don.HanghoaID" name="mahh" />
            <br />
            <span>
                Số Lượng :
                <br />
                <input type="number" min="1" step="1" name="soluong" />
            </span>
            <br />
            <div class="row">
                <div class="col-sm-2">
                    <button type="submit" class="btn btn-primary" style="width:90px;">Mua</button>
                </div>

            </div>
        </form>
    </div>
    <div class="col-sm-4" style="height:500px;border-left-style: double;">
        <div>
            <span style="color: #22c3a7; font-weight: bolder;font-size: 23px;background-color: #dbe4e6; padding: 11px;border-radius: 10px;">Đánh giá Từ Khách Hàng</span>
        </div>
        <br/>
        <div style="margin-bottom: 43px;">
            <h4>Viết Bình Luận ...<span class="glyphicon glyphicon-pencil"></span></h4>
            <form role="form" asp-action="binhluan" asp-controller="NguoiDungs" method="post">
                <div class="form-group">
                    <textarea class="form-control" rows="3" name="bluan"></textarea>
                    <input type="hidden" value="@Model.don.HanghoaID" name="idhh" />
                    <button type="submit" class="btn btn-primary" style="width:30%;float:right;">Comment</button>
                </div>
            </form>

        </div>
        <div style="height:350px; overflow:scroll;">
            @{
                foreach (var item in Model.bluans)
                {
                    <div style="padding-top:40px;">
                        <img />
                        <span style="color: #8586bd;font-size: 20px;background-color: aqua;font-weight: 700;padding: 10px; border-radius: 10px;"> @item.NguoiDung.HoTen</span>
                        <span style="color: #3639c1;font-size: 20px;font-weight: 700;">@item.NoiDung</span>
                        <br />
                        <br />
                        <span>@item.NgayBl</span>
                        <hr />
                    </div>
                }
            }
        </div>

    </div>

    <div class="row" style="margin-left:10px;">
        <h1 style="color:black;font-weight:700">SẢN PHẨM CÙNG LOẠI</h1>
        <hr />
        @foreach (var item in Model.dhhhcungloai)
        {
            <div class="col-sm-2">
                <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
                   asp-route-id="@item.HanghoaID">
                    <img src="~/images/@item.Hinh" style="height:310px;" />
                    <span class="thongtinsanpham">
                        <h4 class="tensanpham">@item.TenHh</h4>
                        <div class="danhmucsanpham">@item.DonGia $</div>
                    </span>
                </a>
            </div>
        }


    </div>

    <div class="row" style="margin-left:10px;">
        <h1 style="color:black;font-weight:700">CÙNG NHÀ CUNG CÂP</h1>
        <hr />
        @foreach (var item in Model.dhhhcungncc)
        {
            <div class="col-sm-2">
                <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
                   asp-route-id="@item.HanghoaID">
                    <img src="~/images/@item.Hinh" style="height:310px;" />
                    <span class="thongtinsanpham">
                        <h4 class="tensanpham">@item.TenHh</h4>
                        <div class="danhmucsanpham">@item.DonGia $</div>
                    </span>
                </a>
            </div>
        }
    </div>
</div>

NETCKTEAM30/NETCKTEAM30/Views/HangHoas/layhanghoa.cshtml
@model IEnumerable<NETCKTEAM30.Models.HangHoaViewModel>
@{
    Layout = "_FrontEnd";
}

<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<link href="~/css/mycss.css" rel="stylesheet" />


<div class="container-fluid">
    <div class="row" style="margin-right:-15px;margin-left:-96px;">
        <div class="products-breadcrumb" style="background-color:#a5c29e;padding:0.5em 14px;">      
            <ul>
                <li><i class="fa fa-home" aria-hidden="true"></i><a href="~/">Home</a><span>|</span></li>
                <li> Sreach <input type="text" id="txtSearch" placeholder="Nhập từ khóa" /></li>
            </ul> 
        </div>

        <div id="results"></div>
        <script>
            $("#txtSearch").keyup(function () {
                $.ajax({
                    url: "/HangHoas/Search",
                    data: { keyword: $(this).val() },
                    type: "GET",
                    success: function (response) {
                        $("#results").html(response);
                    }
                });
            });
        </script>
    </div>

</div>


<div class="row works" style="margin-right:-15px;margin-left:-55px;">
    @foreach (var hh in Model)
    {
        if (hh.GiamGia == 0)
        {
            <div class="col-sm-3">
                <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
                   asp-route-id="@hh.MaHH">
                    <img src="~/images/@hh.Hinh" style="height:310px;width:200px" />
                    <span class="thongtinsanpham">
                        <h4 class="tensanpham">@hh.TenHH</h4>
                        <div class="danhmucsanpham">@hh.GiaBan $</div>
                    </span>
                </a>
            </div>
        }
        else
        {
            double a = (double)hh.GiamGia * 100;
            hh.GiamGia = a;
            <div class="col-sm-3">
                <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
                   asp-route-id="@hh.MaHH">

                    <img src="~/images/@hh.Hinh" style="height:310px;width:200px" />
                    <span class="thongtinsanpham">
                        <h4 class="tensanpham">@hh.TenHH</h4>
                        <span style="color:red;font-weight:700;font-size:20px;">GIẢM @hh.GiamGia %</span>
                        <div class="danhmucsanpham" style="text-decoration: line-through; float:left; margin-top:20px;">@hh.DonGia .000 đ</div>
                        @{
                            double b = (double)(hh.DonGia - ((double)((hh.DonGia * hh.GiamGia) / 100)));
                            hh.DonGia = b;
                        }
                        <div style="float:left;">
                            <span style="color: #0c0c0c;font-size: 10px;margin-left:10px;"> Chỉ còn:</span><span style="color:red;font-size:20px;font-weight:900;">@hh.DonGia .000 đ</span>
                        </div>

                    </span>
                </a>
            </div>
        }

    }
</div>

NETCKTEAM30/NETCKTEAM30/Views/HangHoas/mua.cshtml
@model List<NETCKTEAM30.Models.ChiTietHd>
@{
    ViewData["Title"] = "mua";
}



<meta name="viewport" content="width=device-width" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="~/css/mycss.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<body>
    <div class="row">
        <div class="col-sm-6">
            <div class="row works" style="position:relative;z-index:1;">

                <div id="id01" class="modall" style="display:block;">
                    <div class="dschonmon">
                        <h2 id="dscm">THÔNG TIN GIỎ HÀNG</h2>


                        <table class="table">
                            <thead>
                                <tr>

                                    <th>
                                        Tên Sản Phẩm
                                    </th>
                                    <th>
                                        Đơn Giá
                                    </th>
                                    <th>
                                        Số Lượng
                                    </th>
                                    <th>
                                        Giảm Giá
                                    </th>
                                    <th>
                                        Thành tiền
                                    </th>
                                    <th>
                                        Xóa 
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    double a = (double)item.GiamGia * 100;
                                    item.GiamGia = a;
                                    <tr>
                                        <td>
                                            @item.HangHoa.TenHh
                                        </td>
                                        <td>
                                            @item.DonGia .000 đ
                                        </td>
                                        <td>
                                            @item.SoLuong
                                        </td>
                                        <td>
                                            @item.GiamGia %
                                        </td>
                                        @{ 
                                            item.GiamGia = (double)a / 100;
                                        }
                                        <td>
                                            @item.ThanhTien .000 đ
                                        </td>
                                       
                                        <td>
                                           
                                            <form asp-action="mua" asp-controller="HangHoas" method="post">
                                               <input type="hidden" value="@item.ChiTietHdID" name="id" />
             
                                             <button type="submit" class="btn btn-danger" style="width:90px;">X</button>
                                            </form>
                                        </td>


                                    </tr>
                                }
                            </tbody>
                        </table>
                        <span style="float:right; margin-right:10px;">Tổng cộng:@ViewBag.TongTien .000 đ </span>
                        <br />
                        <br />
                        <a class="btn btn-success" asp-action="index" asp-controller="Home" style="float:left;"> Mua Thêm Sản Phẩm Khác  </a>
                        <br />
                        <a class="btn btn-danger" asp-action="Laphoadon" asp-controller="HangHoas" style="float:right;"> Đặt Hàng  </a>
                    </div>

                </div>
            </div>
        </div>
    </div>



    <script>
        // Get the modal
        var modal = document.getElementById('id01');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>

</body>

NETCKTEAM30/NETCKTEAM30/Views/HangHoas/selectAo.cshtml
@model IEnumerable<NETCKTEAM30.Models.HangHoaViewModel>
@{
    ViewData["Title"] = "selectAo";
}
<meta name="viewport" content="width=device-width" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/mycss.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />


<div class="container-fluid">
    <div class="row">
        <input id="txtSearch" placeholder="Nhập từ khóa" />
        <div id="results"></div>
        <script>
            $("#txtSearch").keyup(function () {
                $.ajax({
                    url: "/HangHoas/Search",
                    data: { keyword: $(this).val() },
                    type: "GET",
                    success: function (response) {
                        $("#results").html(response);
                    }
                });
            });
        </script>
    </div>
   
</div>


<div class="row works">
    @foreach (var hh in Model)
    {
        <div class="col-sm-4">
            <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
               asp-route-id="@hh.MaHH">
                <img src="~/images/@hh.Hinh" />
                <span class="thongtinsanpham">
                    <h4 class="tensanpham">@hh.TenHH</h4>
                    <div class="danhmucsanpham">@hh.GiaBan $</div>
                </span>
            </a>
        </div>
    }
</div>

NETCKTEAM30/NETCKTEAM30/Views/HangHoas/selectQuan.cshtml
@model IEnumerable<NETCKTEAM30.Models.HangHoaViewModel>
@{
    ViewData["Title"] = "selectQuan";
}
<meta name="viewport" content="width=device-width" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - NETCKTEAM30</title>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<link href="~/css/mycss.css" rel="stylesheet" />
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />

<div class="container-fluid">
    <div class="row">
        <input id="txtSearch" placeholder="Nhập từ khóa" />
        <div id="results"></div>
        <script>
            $("#txtSearch").keyup(function () {
                $.ajax({
                    url: "/HangHoas/Search",
                    data: { keyword: $(this).val() },
                    type: "GET",
                    success: function (response) {
                        $("#results").html(response);
                    }
                });
            });
        </script>
    </div>

</div>
<div class="row works">
    @foreach (var hh in Model)
    {
        <div class="col-sm-4">
            <a asp-action="chitiet" asp-controller="HangHoas" class="_hanghoa1"
               asp-route-id="@hh.MaHH">
                <img src="~/images/@hh.Hinh" />
                <span class="thongtinsanpham">
                    <h4 class="tensanpham">@hh.TenHH</h4>
                    <div class="danhmucsanpham">@hh.GiaBan $</div>
                </span>
            </a>
        </div>
    }
</div>